### ISSUE TITLE
Make Install Errors

### ISSUE THREAD

**Issue by justin-iBC** [openmm/openmm-torch#11]
Hi, I followed the instructions in README, generated a Makefile but failed during make install.
I am running on Ubuntu. The error messages was as follows,

[ 35%] Building CXX object platforms/reference/CMakeFiles/OpenMMTorchReference.dir/src/ReferenceTorchKernelFactory.cpp.o
[ 39%] Building CXX object platforms/reference/CMakeFiles/OpenMMTorchReference.dir/src/ReferenceTorchKernels.cpp.o
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp: In function ‘std::vector<OpenMM::Vec3>& extractPositions(OpenMM::ContextImpl&)’:
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp:44:19: error: ‘void*’ is not a pointer-to-object type
     return *data->positions;
                   ^~~~~~~~~
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp: In function ‘std::vector<OpenMM::Vec3>& extractForces(OpenMM::ContextImpl&)’:
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp:49:19: error: ‘void*’ is not a pointer-to-object type
     return *data->forces;
                   ^~~~~~
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp: In function ‘OpenMM::Vec3* extractBoxVectors(OpenMM::ContextImpl&)’:
~/openmm-torch/platforms/reference/src/ReferenceTorchKernels.cpp:54:18: error: invalid conversion from ‘void*’ to ‘OpenMM::Vec3*’ [-fpermissive]
     return data->periodicBoxVectors;
            ~~~~~~^~~~~~~~~~~~~~~~~~
platforms/reference/CMakeFiles/OpenMMTorchReference.dir/build.make:86: recipe for target 'platforms/reference/CMakeFiles/OpenMMTorchReference.dir/src/ReferenceTorchKernels.cpp.o' failed
make[2]: *** [platforms/reference/CMakeFiles/OpenMMTorchReference.dir/src/ReferenceTorchKernels.cpp.o] Error 1

It seems that the pointer points to void in the source code of ReferenceTorchKernels.cpp. Any suggestions? Thanks.

**Comment by peastman** [comment]
You'll need to compile against the latest OpenMM source code from the repository.  The signature of that field has changed since the last release.

**Comment by otayfuroglu** [comment]
Hello every one,
I compiled openMM from source and I followed the instructions in README for compile  and install openmm-torch, but failed during make install.

my system : centos 7
libtorch version: 1.7.0.dev20200924+cu92
gcc version: 9.2
gxx version: c++14

The error messages was as follows,

Scanning dependencies of target CopyTestFiles                                                                                                      [2/1823]
[  3%] CMake-copying file /home/modellab/Downloads/openmm-torch/tests/central.pt to /home/modellab/Downloads/openmm-torch/build/tests/central.pt
[  7%] CMake-copying file /home/modellab/Downloads/openmm-torch/tests/periodic.pt to /home/modellab/Downloads/openmm-torch/build/tests/periodic.pt
[  7%] Built target CopyTestFiles
Scanning dependencies of target OpenMMTorch
[ 10%] Building CXX object CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForce.cpp.o
[ 14%] Building CXX object CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForceImpl.cpp.o
[ 17%] Building CXX object CMakeFiles/OpenMMTorch.dir/serialization/src/TorchForceProxy.cpp.o
[ 21%] Building CXX object CMakeFiles/OpenMMTorch.dir/serialization/src/TorchSerializationProxyRegistration.cpp.o
[ 25%] Linking CXX shared library libOpenMMTorch.so
[ 25%] Built target OpenMMTorch
Scanning dependencies of target TestSerializeTorchForce
[ 28%] Building CXX object serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o
[ 32%] Linking CXX executable ../../TestSerializeTorchForce
CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: In function `testSerialization()':
TestSerializeTorchForce.cpp:(.text+0x21a): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: In function `void OpenMM::XmlSerializer::serialize<TorchPlugin::TorchForce>(TorchPlu$in::TorchForce const*, std::string const&, std::ostream&)':
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11To$chPlugin10TorchForceEEEvPKT_RKSsRSo]+0x66): undefined reference to `OpenMM::SerializationNode::setName(std::string const&)'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11To$chPlugin10TorchForceEEEvPKT_RKSsRSo]+0xcd): undefined reference to `OpenMM::SerializationNode::hasProperty(std::string const&) const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11To$chPlugin10TorchForceEEEvPKT_RKSsRSo]+0x104): undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11To$chPlugin10TorchForceEEEvPKT_RKSsRSo]+0x154): undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11To$chPlugin10TorchForceEEEvPKT_RKSsRSo]+0x191): undefined reference to `OpenMM::SerializationNode::setStringProperty(std::string const&, std::string const&)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::Platform::createKernel(std::string const&, OpenMM::ContextImpl&) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::setIntProperty(std::string const&, int)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationProxy::SerializationProxy(std::string const&)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getStringProperty(std::string const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [TestSerializeTorchForce] Error 1
make[1]: *** [serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/all] Error 2
make: *** [all] Error 2

Any suggestions? Thank you ..

**Comment by raimis** [comment]
All undefined symbols contain `std::string`, which mean OpenMM was compiled for the old C++ ABI (https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), while OpenMM-Torch was compiled for the new C++11 ABI.

**Comment by otayfuroglu** [comment]
Hello @raimis, thank you very much.
As far as I know, openmm-torch cannot compile c++11, it requires c++14. 
How do I compile openmm with c++14 ?.
Thereby, openmm-torch and openmm will compiled same ABI standard.

best

**Comment by peastman** [comment]
The name is confusing, but this is actually separate from the choice of C++ version.  They called it the "C++11 ABI" because they needed it to support a new feature introduced in C++11.  But that doesn't mean there's a different ABI for each C++ version.  C++14 uses exactly the same ABI.

**Comment by jaimergp** [comment]
Now that [conda forge packages are available](https://anaconda.org/conda-forge/openmm-torch), this can be closed, I guess? [The recipe files can be checked here](https://github.com/conda-forge/openmm-torch-feedstock/tree/master/recipe) if anybody wants to try local.

**Comment by peastman** [comment]
Agreed.  Compiling and getting everything consistent can still be difficult, but now there should be less need for people to compile it themselves.
