### ISSUE TITLE
'TorchForce' object has no attribute 'setProperty'

### ISSUE THREAD

**Issue by Dead-fisher** [openmm/openmm-torch#112]
Hi,

The README file states we can use `setProperty` to enable cuda graph, but it seems that the openmm-torch code from conda install doesn't implement this functionality. As the codes gives me:

```
Traceback (most recent call last):
  File "xxx/simulation_rid.py", line 41, in <module>
    torch_force.setProperty("useCUDAGraphs", "true")
AttributeError: 'TorchForce' object has no attribute 'setProperty'
```

**Comment by RaulPPelaez** [comment]
Which version do you have installed? Could you post the output of ```$mamba list``` ?

**Comment by RaulPPelaez** [comment]
Actually, the CUDA graph functionality has not been included in a conda release yet. Latest release is from mid 2022. You will have to build from source.
@raimis, @peastman , do you think we could prepare a new release or should we wait for #106 to get pytorch2 compatibility at the same time?

**Comment by Dead-fisher** [comment]
Thanks for your quick reply. I just used the latest version now, 
```
conda create -n test python=3.9 pytorch=1.11.0=*cuda* openmm-torch openmm -c conda-forge -c pytorch
```
where the version info is:
```
openmm                    8.0.0            py39h7d85326_1    conda-forge
openmm-torch              1.0             cuda112py39h47d0fa4_1    conda-forge
```
It will be great if you can merge a new version and release it to get Pytorch2 compatibility.

**Comment by RaulPPelaez** [comment]
The latest release should have the requested funcionality. #113

**Comment by raimis** [comment]
OpenMM-Torch 1.1 with the CUDA Graph support has been released (https://github.com/openmm/openmm-torch/releases/tag/v1.1).
