### ISSUE TITLE
New release (v1.1)

### ISSUE THREAD

**Issue by RaulPPelaez** [openmm/openmm-torch#113]
#106 has been merged, and some other functionalities are not released yet (e.g #101, #97 ,...)
Maybe its time for a new release?
cc @peastman @raimis

**Comment by RaulPPelaez** [comment]
I see it went from 0.8 to 1.
Current recipe points to https://github.com/openmm/openmm-torch/commit/994f92fde4ce710a4db5557b6bc22756d5f9d2b1
Perhaps the sensible thing is to tag that commit with v1.0 and release another tag with the latest commit called v1.1 or something like that?

**Comment by raimis** [comment]
@peastman why there is a release on conda-forge (https://github.com/conda-forge/openmm-torch-feedstock/pull/33) without tagging in the repo?

**Comment by raimis** [comment]
OK! I'll create the 1.0 release retrospectively and proceed with 1.1.

**Comment by raimis** [comment]
1.0 is done: https://github.com/openmm/openmm-torch/releases/tag/v1.0

**Comment by raimis** [comment]
1.1 is done: https://github.com/openmm/openmm-torch/releases/tag/v1.1

**Comment by raimis** [comment]
https://github.com/conda-forge/openmm-torch-feedstock/pull/36

**Comment by RaulPPelaez** [comment]
Closign this as completed
