### ISSUE TITLE
Is it possible to use openmm-torch to apply force on only several atoms or CVs

### ISSUE THREAD

**Issue by JinyinZha** [openmm/openmm-torch#119]
I am trying to use openmm-torch to add several force to dihedrals. (Namely, the force is in form of F(φ1,φ2,...φn,ψ1,ψ2,...,ψn)) However openmm-torch was made for a force in the form of F(**x**1,**x**2,...**x**n)), where **x** is the coordinate of atom. I attempted to add an additional part converting **x** into dihedrals in the network structure, and then input dihedrals into my network. However, it turns out that the grad is reduced.

> Traceback (most recent call last):
  File "/home/jyzha/project/enhanced_sampling/networks/test_openmm2.py", line 94, in <module>
    simulation.minimizeEnergy()
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/openmm.py", line 17208, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException: grad can be implicitly created only for scalar outputs
Exception raised from _make_grads at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1670027390539/work/torch/csrc/autograd/autograd.cpp:57 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x68 (0x7fc88ffb8d28 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xe8 (0x7fc88ff7eb58 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x3c1577d (0x7fc8c6a6e77d in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<bool>, bool, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x42 (0x7fc8c6a6fd42 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x3c62ca1 (0x7fc8c6abbca1 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #5: at::Tensor::_backward(c10::ArrayRef<at::Tensor>, c10::optional<at::Tensor> const&, c10::optional<bool>, bool) const + 0x49 (0x7fc8c3f26359 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: TorchPlugin::CudaCalcTorchForceKernel::execute(OpenMM::ContextImpl&, bool, bool) + 0xed2 (0x7fc8ca9a6622 in /home/jyzha/software/anaconda3/envs/openmm/lib/plugins/libOpenMMTorchCUDA.so)
frame #7: OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) + 0xc9 (0x7fc93a770789 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #8: OpenMM::Context::getState(int, bool, int) const + 0x15e (0x7fc93a76de5e in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #9: <unknown function> + 0x17bb54 (0x7fc93a7d7b54 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #10: <unknown function> + 0x17c31a (0x7fc93a7d831a in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #11: lbfgs + 0x58c (0x7fc93a83606c in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #12: OpenMM::LocalEnergyMinimizer::minimize(OpenMM::Context&, double, int) + 0x75d (0x7fc93a7d8ddd in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.8.0)
frame #13: <unknown function> + 0x118d86 (0x7fc93ab6dd86 in /home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/_openmm.cpython-39-x86_64-linux-gnu.so)
<omitting python frames>

If the additional conversion is  changed to directly " return x" (where x is the input, namely no changes),  the code could run well (Indeed, I changed my network to fit the dimension of input. ) I found any calculations to the input of forward function would cause this error. 

I am wondering whether my attempt could be realized. If could, then how? I am looking forward to your answer. Thank you~

**Comment by RaulPPelaez** [comment]
Could you please provide a minimum reproducer code?
As long as your model takes positions as inputs and outputs energies and optionally forces it should be fine.

**Comment by RaulPPelaez** [comment]
Looking at the particular error, it seems like your model is not returning forces explicitly. This makes openmm-torch automatically compute them by calling backwards on your model.
The error you post seems to indicate that your model cannot be backpropagated. 
I can think of a number of reasons why this would happen:
- The input to the network is not the positions
- The output is not the energy (a tensor with a single number)
- You have non autograd compatible code in your forward

**Comment by RaulPPelaez** [comment]
I would say the eror in your network stems from this:
```python
    self.encoder = encoder# a MLP network that output a 1x2 tensor
```
Your network is supposed to return only one number, the energy.

**Comment by JinyinZha** [comment]
You are right! I have successfully fixed the problem. Thanks a lot~
