### ISSUE TITLE
Compatability with Intel Ponte Vecchio GPUs?

### ISSUE THREAD

**Issue by jharrymoore** [openmm/openmm-torch#138]
Hi,

I am trying to understand what would be needed to run a neural network potential-driven simulation on the Intel Ponte Vecchio GPUs.  From my initial testing, openMM can target the GPU fine with the openCL platform, and pytorch models can be run via Intel's pytorch extensions which contains the custom SYCL kernels (https://github.com/intel/intel-extension-for-pytorch).

From looking at the openmm-torch code, I see there is an openCL backend, however from [this discussion](https://github.com/openmm/openmm-torch/issues/111#issuecomment-1631111473) it does not actually execute the torch kernel on the GPU.

I wondered if you could give me a pointer on what I would need to modify in openmm-torch to run a simulation using the openCL backend with a pytorch model using the intel extension?

**Comment by peastman** [comment]
Compare the [OpenCL](https://github.com/openmm/openmm-torch/blob/master/platforms/opencl/src/OpenCLTorchKernels.cpp) and [CUDA](https://github.com/openmm/openmm-torch/blob/master/platforms/cuda/src/CudaTorchKernels.cpp) implementations of the kernel.  The CUDA version puts the module and all the input and output tensors onto the correct device:

https://github.com/openmm/openmm-torch/blob/4fe23f6869806dce9246fb98cff6c84c06b39d9e/platforms/cuda/src/CudaTorchKernels.cpp#L77-L83

You would need to make the OpenCL version do the same thing.  The CUDA implementation also does other things that might not be relevant.  It copies data directly on the GPU without bringing it back to the CPU.  I don't think that will be possible with OpenCL, but it's only a minor optimization in most cases.  It also has code for recording CUDA graphs, which isn't relevant to OpenCL.

**Comment by jharrymoore** [comment]
Hi Peter,

Many thanks for your pointers above - I now have the model running on the XPU, and the unit tests compute energies and forces properly, however the OpenCL unit tests are segfaulting when I try to send the resulting tensor to the openMM OpenCLArray.

https://github.com/openmm/openmm-torch/blob/4fe23f6869806dce9246fb98cff6c84c06b39d9e/platforms/opencl/src/OpenCLTorchKernels.cpp#L99-L103

I am using compiler supplied OpenCL and OpenMM 8.1 from conda-forge.  

Running the unit tests under gdb, I get the following backtrace

```
#0  0x00007fff3d9c9f53 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffec0197a13 in NEO::MemoryManager::allocateInternalGraphicsMemoryWithHostCopy(unsigned int, std::bitset<4ul>, void const*, unsigned long) ()
   from /usr/lib64/intel-opencl/libigdrcl.so
#2  0x00007ffec01034f6 in NEO::CommandStreamReceiver::createAllocationForHostSurface(NEO::HostPtrSurface&, bool) () from /usr/lib64/intel-opencl/libigdrcl.so
#3  0x00007ffebff75996 in NEO::CommandQueueHw<NEO::XeHpcCoreFamily>::enqueueWriteBuffer(NEO::Buffer*, unsigned int, unsigned long, unsigned long, void const*, NEO::GraphicsAllocation*, unsigned int, _cl_event* const*, _cl_event**) () from /usr/lib64/intel-opencl/libigdrcl.so
#4  0x00007ffebfcd07b4 in clEnqueueWriteBuffer () from /usr/lib64/intel-opencl/libigdrcl.so
#5  0x00007ffff7fe34a9 in clEnqueueWriteBuffer ()
   from /usr/local/dawn/software/spack/opt-2023-12-22/linux-rocky8-sapphirerapids/gcc-13.2.0/intel-oneapi-compilers-2024.0.0-znjudqsiaf6x5u2rxdtymf6ss55nmimw/compiler/2024.0/lib/libOpenCL.so.1
#6  0x00007fff3e48cbdf in OpenMM::OpenCLArray::uploadSubArray(void const*, int, int, bool) () from /home/jhm72/miniconda3/lib/libOpenMMOpenCL.so
#7  0x00007ffff7baadeb in OpenMM::OpenCLArray::upload (this=0x9132730, data=0xff00ffffffc00800, blocking=true) at /home/jhm72/miniconda3/include/openmm/opencl/OpenCLArray.h:217
#8  0x00007ffff7ba8e05 in TorchPlugin::OpenCLCalcTorchForceKernel::execute (this=0x91326b0, context=..., includeForces=true, includeEnergy=true)
    at /home/jhm72/rds/hpc-work/software/openmm-torch/platforms/opencl/src/OpenCLTorchKernels.cpp:132
#9  0x00007ffff79620cf in TorchPlugin::TorchForceImpl::calcForcesAndEnergy (this=0x7a1a310, context=..., includeForces=true, includeEnergy=true, groups=-1)
    at /home/jhm72/rds/hpc-work/software/openmm-torch/openmmapi/src/TorchForceImpl.cpp:57
#10 0x00007fff3e863109 in OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) () from /home/jhm72/miniconda3/lib/libOpenMM.so.8.1
#11 0x00007fff3e860772 in OpenMM::Context::getState(int, bool, int) const () from /home/jhm72/miniconda3/lib/libOpenMM.so.8.1
#12 0x0000000000408841 in testForce (outputsForces=false) at /home/jhm72/rds/hpc-work/software/openmm-torch/platforms/opencl/tests/TestOpenCLTorchForce.cpp:75
#13 0x000000000040b85c in main (argc=2, argv=0x7fffffff6268) at /home/jhm72/rds/hpc-work/software/openmm-torch/platforms/opencl/tests/TestOpenCLTorchForce.cpp:180
```

Do you have any suggestions on what might be going wrong?

**Comment by jharrymoore** [comment]
Ah, found my mistake - the force tensor was on the wrong device
