### ISSUE TITLE
OpenCL tests failing on build from source

### ISSUE THREAD

**Issue by jharrymoore** [openmm/openmm-torch#139]
I am attempting to build openmm-torch from source - the compilation proceeds OK following Stephen's notes [here](https:/}github.com/sef43/openmm-torch/blob/master/INSTALL.md), however the OpenCL tests are all segfaulting for me (the reference and CUDA tests all pass).  In the GH CI all the recent runs seem to fail before running the c++ tests - could I check whether you can reproduce this on your end or whether it's an issue with my build? I have attached ctest logs and the build cache - let me know if there's anything else that would be helpful.

[CMakeCache.txt](https://github.com/openmm/openmm-torch/files/14937672/CMakeCache.txt)
[LastTest.log](https://github.com/openmm/openmm-torch/files/14937826/LastTest.log)

**Comment by peastman** [comment]
Segfaults usually indicate some sort of a binary incompatibility.  You need OpenMM, OpenMM-Torch, and PyTorch to all be compiled in compatible ways (same ABI, etc.).  You said you're compiling OpenMM-Torch from source.  What about the others?  Where do you install them from?

If it's only the OpenCL tests that segfault, that also suggests it may be an incompatibility with the OpenCL implementation.  Which one do you use?

Try running one of the tests inside gdb.  Let it run until it segfaults, then type `bt` to get a stack trace for where it happened.  Post the full trace here.  It might provide a clue.

**Comment by jharrymoore** [comment]
right you are -  I was using OpenCL that was installed with conda.  Switching to the compiler-provided OpenCL.so does the trick.  Many thanks for the pointer!
