### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by raimis** [openmm/openmm-torch#14]
Currently there is no a conda package of  _OpenMM-Torch_, but it would we very useful to simplify deployment.

Problems/progress to make a _conda-forge_-compatible package:
- [ ] Compatible _OpenMM_ package
   - The _Omnia_ package (https://anaconda.org/omnia/openmm) is not _conda-forge_-compatible
     - It is build with pre-C++11 ABI
   - _OpenMM_ >= 7.5 is required due to API changes (#11)
   - The _conda-forge_ package is underway (https://github.com/conda-forge/openmm-feedstock)
     - Test packages already available (https://anaconda.org/conda-forge/openmm)
- [ ] Compatible _PyTorch_ package
   - The _Anaconda_ package (https://anaconda.org/anaconda/pytorch) has just 1.4.0 version  (>1.4.0 is CPU only)
     - _TorchANI_ 2.2 requires _PyTorch_ >=1.5.0
     - _TorchANI_ 1.2 works with _PyTorch_ 1.4.0, but does not support _ANI-2x_
  - The _conda-forge_ package (https://anaconda.org/conda-forge/pytorch-cpu) is CPU only
    - GPU-enabled package is underway (https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7)
  - The _PyTorch_ package (https://anaconda.org/pytorch/pytorch) is not _conda-forge_-compatible
     - It is built with pre-C++11 ABI
     - It requires _glibc_ 2.14 (CDT provides just _glibc_ 2.12)
  - _libTorch_ libraries (https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.6.0.zip) are not compatible with _CentOS_ 7
    - They require _glibc_ 2.23 (_CentOS_ 7 provides just _glibc_ 2.17)
- [ ] Conda recipe for  _OpenMM-Torch_
  - There is a partially working recipe (#9)
    - It has to be moved to the _conda-forge_ feedstock.

**Comment by raimis** [comment]
Ping who might be interested: @peastman @jchodera @jaimergp @stefdoerr @giadefa

**Comment by peastman** [comment]
That's a good summary, thanks.

Some posters at https://github.com/pytorch/pytorch/issues/17492 claim the latest package on the `pytorch` channel has moved to the C++11 ABI.  I'll investigate and see if that's true.

**Comment by raimis** [comment]
Nope, PyTorch 1.6.0 in PyTorch channel (https://anaconda.org/pytorch/pytorch) is build with the old C++ ABI.

**Comment by jchodera** [comment]
Also good news https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7#issuecomment-562220076
> @henryiii there is a plan now for a GPU enabled PyTorch package on conda-forge, supported by the PyTorch team. An update on that plan will follow soon.

**Comment by hadim** [comment]
FYI `torchani` is available on conda-forge: https://github.com/conda-forge/torchani-feedstock

**Comment by jaimergp** [comment]
This can get closed after https://github.com/conda-forge/staged-recipes/pull/13659 is merged 😎

You can try the [artifacts](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=262764&view=artifacts&pathAsName=false&type=publishedArtifacts) if you want, but the tests pass so far :)

**Comment by jaimergp** [comment]
`openmm-torch` is now on Conda Forge:

* https://github.com/conda-forge/openmm-torch-feedstock
* https://anaconda.org/conda-forge/openmm-torch

**Comment by raimis** [comment]
Thanks @jaimergp!

**Comment by raimis** [comment]
Probably, we should update `README.md`, so everybody is aware.

**Comment by jaimergp** [comment]
Oh, right! Added PR!

**Comment by jchodera** [comment]
Woohoo! 

@peastman : Once the README is fixed, is it OK if we tweet about this?

**Comment by peastman** [comment]
Fine with me.

**Comment by jchodera** [comment]
I'll tweet after https://github.com/openmm/openmm-torch/pull/21 is merged.
