### ISSUE TITLE
Define per-particle parameters in TorchForce

### ISSUE THREAD

**Issue by ChiahsinChu** [openmm/openmm-torch#150]
Hi,

I would like to know if using per-particle parameters (e.g., charges) in the custom force field is possible. I assume it isn't if I don't get wrong with the doc and the codes. Do you have any suggestions if I would like to modify the codes?

Thanks.

**Comment by peastman** [comment]
Your model can contain whatever parameters you want.  [Here is an example](https://github.com/openmm/nutmeg/blob/c8cbe9162efbfbfa03b59f53a36c22af4b1f51d3/nutmegpotentials/nutmegpotential.py#L53-L73) of a class that does that.  There are per-particle parameters (`types` and `node_attrs`) that get passed to the model's constructor, stored as parameters, and used in calculating the energy.

**Comment by ChiahsinChu** [comment]
Many thanks!
