### ISSUE TITLE
Release v1.5

### ISSUE THREAD

**Issue by RaulPPelaez** [openmm/openmm-torch#154]
Several features have been included since the last release (last year), should we make a new one?

## What's Changed
* Can compute parameter derivatives by @peastman in https://github.com/openmm/openmm-torch/pull/143
* Attempts at fixing CI by @peastman in https://github.com/openmm/openmm-torch/pull/144
* Freeze pytorch model by @peastman in https://github.com/openmm/openmm-torch/pull/148
* Add energy derivatives to README by @RaulPPelaez in https://github.com/openmm/openmm-torch/pull/145
* Serialize property values by @peastman in https://github.com/openmm/openmm-torch/pull/152
* Update Mac build to newer versions by @peastman in https://github.com/openmm/openmm-torch/pull/153

@peastman is there anything you would like to add in before v1.5?

**Comment by jharrymoore** [comment]
It would be great to have a release on conda-forge. We are interested in using the parameter derivatives implemented here, without having to build the environment from source.

**Comment by peastman** [comment]
1.5 is now up.
