### ISSUE TITLE
Version scheme

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm-torch#20]
Can we tag `master` with `v0.1`  or whatever version scheme you prefer and create a GH release? That way I can use it for the [imminent conda package](https://github.com/conda-forge/staged-recipes/pull/13659) :D

**Comment by peastman** [comment]
Done!  https://github.com/openmm/openmm-torch/releases/tag/v0.1

**Comment by jaimergp** [comment]
Thanks!
