### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-torch#22]
@jaimergp : Any ideas on how we might be able to set up CI here now that we are able to install `openmm` an `pytorch` from conda-forge? 

In principle, we should at least be able to test the Reference and OpenCL platforms, and we may even be able to test the CUDA platform if we wanted to wire in @swails Jenkins until GPU CI becomes available.

**Comment by jaimergp** [comment]
Setup would be similar to OpenMM's. I'll get to it once the backlog clears up a bit!

**Comment by jaimergp** [comment]
And the same applies to openmm-plumed!

**Comment by swails** [comment]
> In principle, we should at least be able to test the Reference and OpenCL platforms, and we may even be able to test the CUDA platform if we wanted to wire in @swails Jenkins until GPU CI becomes available.

Jenkins installs and tests OpenMM in [this container](https://github.com/Amber-MD/common-dockerfiles/blob/master/cuda-opencl/Dockerfile).

If you update that Dockerfile in a PR, it'll update the image automatically and pull it for all OpenMM GPU builds.
