### ISSUE TITLE
Naming: Should this be openmm-torch or openmm-pytorch?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-torch#24]
@peastman @giadefa @jaimergp : Now that Torch has become pytorch, what do you think about renaming this to `openmm-pytorch` to be more familiar to everyone using pytorch?

**Comment by giadefa** [comment]
I don't mind. The actual python module name of pytorch is torch.

**Comment by jaimergp** [comment]
Now that we have put a package on conda-forge, named `openmm-torch`, chainging the name could lead to some (mild) confusion. PyTorch is only the "brand" as far as I know; internals, as Gianni points out, still use `torch`. `.so` libraries are also named [`libtorch*`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=261195&view=logs&j=c8d040bd-2103-5051-ff1e-9fedef6965c4&t=7e7c916f-77a4-5a43-8634-15efa9c53ff9&l=5890).

I'd rather stay with `openmm-torch` if we haven't heard of any issues with the current name so far.

**Comment by jchodera** [comment]
The `openmm-torch` has only been on conda-forge for two days, and `torch` is a module of the real package named `pytorch`, which is now the name that everybody uses. I'm just worried that not using `pytorch` will cause confusion.

**Comment by jaimergp** [comment]
I'll have to check if package renaming is allowed or we need to provide an "alias" package. The Python wrapper package for this projects is called `openmmtorch` too. Is that going to change to `openmmpytorch` too?

**Comment by jchodera** [comment]
@peastman : Any thoughts/preferences?

**Comment by peastman** [comment]
I think my preference is to leave things as they are.  Either name would be fine, so why create extra work for ourselves and our users by changing it?
