### ISSUE TITLE
Running ANI potentials with openmm-torch

### ISSUE THREAD

**Issue by jeff231li** [openmm/openmm-torch#26]
Hi, is there a working example/script for running a simulation with `torchANI` potentials in OpenMM with the `openmm-torch` plugin?

**Comment by peastman** [comment]
We're developing a simplified API for this.  It's still early in development, but it should be usable already, so give it a try: https://github.com/openmm/openmm-ml.

```python
from openmmml import MLPotential
potential = MLPotential('ani2x')
system = potential.createSystem(topology)
```

For documentation see https://github.com/openmm/openmm-ml/blob/main/openmmml/mlpotential.py.

**Comment by jeff231li** [comment]
I was able to add the ANI potential to my system using the `createMixedSystem` function

``` python
pdbfile = app.PDBFile("mol_waterbox.pdb")
with open("mol_waterbox.xml", "r") as f:
    mm_system = openmm.XmlSerializer.deserialize(f.read())    

potential = MLPotential('ani2x')
ml_atoms  = [atom.index for atom in pdbfile.topology.atoms() if atom.residue.name == "GZL"]
ml_system = potential.createMixedSystem(pdbfile.topology, mm_system, ml_atoms)
```

but when I run `minimizeEnergy` or an MD run I get the error message below:
``` 
---------------------------------------------------------------------------
OpenMMException                           Traceback (most recent call last)
<ipython-input-5-0d9307e0e09c> in <module>
----> 1 simulation.step(10)

~/anaconda3/envs/openmm-torch/lib/python3.9/site-packages/simtk/openmm/app/simulation.py in step(self, steps)
    130     def step(self, steps):
    131         """Advance the simulation by integrating a specified number of time steps."""
--> 132         self._simulate(endStep=self.currentStep+steps)
    133 
    134     def runForClockTime(self, time, checkpointFile=None, stateFile=None, checkpointInterval=None):

~/anaconda3/envs/openmm-torch/lib/python3.9/site-packages/simtk/openmm/app/simulation.py in _simulate(self, endStep, endTime)
    200                 if endTime is not None and datetime.now() >= endTime:
    201                     return
--> 202             self.integrator.step(stepsToGo)
    203             self.currentStep += stepsToGo
    204             if anyReport:

~/anaconda3/envs/openmm-torch/lib/python3.9/site-packages/simtk/openmm/openmm.py in step(self, steps)
  13599             the number of time steps to take
  13600         """
> 13601         return _openmm.LangevinIntegrator_step(self, steps)
  13602 
  13603     def __init__(self, *args):

OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torchani/aev.py", line 35, in forward
      _2, cell0 = False, unchecked_cast(Tensor, cell)
    if _2:
      aev0 = __torch__.torchani.aev.compute_aev(species, coordinates, self.triu_index, (self).constants(), (7, 16, 112, 32, 896), None, )
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      aev = aev0
    else:
  File "code/__torch__/torchani/aev.py", line 110, in compute_aev
  species120 = torch.index_select(species12, 1, even_closer_indices)
  vec1 = torch.index_select(vec, 0, even_closer_indices)
  central_atom_index, pair_index12, sign12, = _7(atom_index122, )
                                              ~~ <--- HERE
  _22 = torch.slice(species120, 0, 0, 9223372036854775807, 1)
  _23 = annotate(List[Optional[Tensor]], [None, pair_index12])
  File "code/__torch__/torchani/aev.py", line 267, in triple_by_molecule
  sorted_local_index12 = torch.index(_85, _86)
  _87 = torch.index_select(_78(counts, ), 0, pair_indices)
  sorted_local_index120 = torch.add_(sorted_local_index12, _87, alpha=1)
                          ~~~~~~~~~~ <--- HERE
  _88 = annotate(List[Optional[Tensor]], [sorted_local_index120])
  local_index12 = torch.index(rev_indices, _88)

Traceback of TorchScript, original code (most recent call last):
  File "/home/jsetiadi/anaconda3/envs/openmm-torch/lib/python3.9/site-packages/torchani/aev.py", line 301, in compute_aev

    # compute angular aev
    central_atom_index, pair_index12, sign12 = triple_by_molecule(atom_index12)
                                               ~~~~~~~~~~~~~~~~~~ <--- HERE
    species12_small = species12[:, pair_index12]
    vec12 = vec.index_select(0, pair_index12.view(-1)).view(2, -1, 3) * sign12.unsqueeze(-1)
  File "/home/jsetiadi/anaconda3/envs/openmm-torch/lib/python3.9/site-packages/torchani/aev.py", line 246, in triple_by_molecule
    mask = (torch.arange(intra_pair_indices.shape[2], device=ai1.device) < pair_sizes.unsqueeze(1)).flatten()
    sorted_local_index12 = intra_pair_indices.flatten(1, 2)[:, mask]
    sorted_local_index12 += cumsum_from_zero(counts).index_select(0, pair_indices)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

    # unsort result from last part
RuntimeError: The size of tensor a (1691) must match the size of tensor b (1707) at non-singleton dimension 1
```

**Comment by peastman** [comment]
I'd like to try to reproduce this.  Would it be possible for you to post a complete test case, including the full script and input files?

**Comment by jeff231li** [comment]
@peastman Attached is the full python script and input files I used. Also, below are the software versions I have in my conda environment.

- openmm v7.5.0
- openmm-torch v0.1
- torchani v2.2
- torchvision v0.8.2
- pytroch v1.7.1

[molecule.zip](https://github.com/openmm/openmm-torch/files/6114359/molecule.zip)

**Comment by peastman** [comment]
Thanks!  I can reproduce it.  I have an idea what the problem might be, and I'm working on it.  Unfortunately I'm currently getting segfaults inside libtorch, probably due to incompatibilities between different versions of libraries, so that's making it harder to debug...

**Comment by victorprincipe** [comment]
> Thanks! I can reproduce it. I have an idea what the problem might be, and I'm working on it. Unfortunately I'm currently getting segfaults inside libtorch, probably due to incompatibilities between different versions of libraries, so that's making it harder to debug...

Hi, I'm trying to run a mixed simulation using ANI for the ligand in a protein-ligand complex. I'm having this same issue with segfaults inside libtorch. Could you please let me know if you manage to resolve it and, if so, how you did it? Thanks in advance!

**Comment by peastman** [comment]
The segfaults came from having two different copies of libtorch.  There was a standalone copy that I compiled against, but at runtime I needed to make sure that copy was *not* in the library path.  Instead, I needed to add the path to the one installed by conda.  Even though they were both supposedly the same version, that led to a crash.

I'm now trying to track down the tensor size mismatch shown in the log above.  It's happening in a calculation deep inside Torch-ANI.

**Comment by victorprincipe** [comment]
Ok great thanks for letting me know, I'll see if I can debug by doing the same

**Comment by peastman** [comment]
Then again, some of the segfaults have started reappearing.  There must be something more going on.

**Comment by peastman** [comment]
It looks like this error has nothing to do with OpenMM.  I was able to reproduce it using just PyTorch and TorchANI.  See https://github.com/aiqm/torchani/issues/586.

**Comment by jeff231li** [comment]
@peastman Thank you for investigating this issue. I was able to reproduce the error message with the example script you posted on the `torchani` Github page. It looks like the bug in PyTorch 
 is fixed with the release of `v1.8.0`. However, I think `openmm-torch`, as installed from conda, is not compatible with PyTorch `v1.8.0`. I'm getting the error below when I rerun my `openmm-ml` script.
```
simtk.openmm.OpenMMException: Specified a Platform for a Context which does not support all required kernels
```
I also tried running a [script](https://github.com/openmm/openmm-torch/files/6146544/script_omm_torch.zip) based on the example from `README.md` (central harmonic potential) that doesn't call `torchANI` and also received the same error. I suspect this is an issue with conflicting dependencies when installing with conda... different cuda versions? I don't get this error when I downgrade PyTorch back to `v1.7.1`.

**Comment by peastman** [comment]
@jaimergp does the conda package specifically depend on PyTorch 1.7?  If so, can we update it to 1.8?

**Comment by jaimergp** [comment]
The packages are pinned against the major version (so it should work with pytorch >=v1.7.1,<2.0.0a), but maybe it should be pinned against major.minor (>=1.7,<1.8.0a). I will release new packages with this in mind and rebuild for pytorch 1.8.

**Comment by peastman** [comment]
I think pinning to the major version is fine.  The issues are that 1) PyTorch 1.7.1 has a bug that prevents this from working, so we should require 1.8 or higher, and 2) if possible we should only set a lower bound, so we don't prevent conda from upgrading to 1.9 when it gets released.

**Comment by jaimergp** [comment]
According to this https://github.com/pytorch/pytorch/issues/28754, we might need to pin even stricter because there are no ABI guarantees across versions. The lower bound is going to be on the one used to build the plugin, the upper bound can be chosen, but I'd argue major.minor is a conservative compromise.

**Comment by peastman** [comment]
I think that issue may be out of date.  They say

> the core, dispatcher, C++ API are in high flux. I doubt that this would change for atleast another 6 months.

But that was written a year and a half ago.

> I'd argue major.minor is a conservative compromise.

Are we willing to commit to releasing a new build for every new PyTorch build that gets released?  If not, that isn't a viable approach.  It's an unfortunate consequence of the broken dependency model used by Python and conda.  If we require a specific PyTorch version, and another package requires a different specific version, then it's impossible to install those two packages into the same environment.

**Comment by jaimergp** [comment]
We might need to expand the build matrix to include recent major.minor versions, as we do with `cudatoolkit`. I asked about it in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/40.

**Comment by peastman** [comment]
It sounds like they want us to do separate builds for each PyTorch version.  Shall we go ahead and do a build for 1.8?  We need to get it out, since 1.7.1 has a serious bug.

**Comment by jaimergp** [comment]
Sure thing, I'll do it this week!

**Comment by jeff231li** [comment]
When the new `openmm-torch` is out on Conda to work with `pytorch v1.8`, will this work with `openmm v7.5`, or will I need to install the nightly build? This seems to be the case from what I gather in https://github.com/openmm/openmm-torch/issues/27.

**Comment by peastman** [comment]
It should work with 7.5.  But according to https://github.com/aiqm/torchani/issues/586, upgrading to PyTorch 1.8 doesn't entirely fix the problem.  They've figured out a way to work around it through a change in TorchANI.

**Comment by jeff231li** [comment]
I tried the fix from https://github.com/aiqm/torchani/issues/586 with openmm v7.5 & pytorch v1.7.1 and it seems to work only if I don't add a `StateDataReporter` object because of the GIL issue (fixed in the upcoming openmm v7.5.1). I also tried installing the nightly build of openmm using `conda install -c conda-forge -c omnia-dev openmm` and my script works but only on the CPU. If I run on the GPU I get the following error:
```
Traceback (most recent call last):
  File "run_openmm_ml.py", line 44, in <module>
    simulation.minimizeEnergy()
  File "/home/jsetiadi/anaconda3/envs/openmm-ml/lib/python3.7/site-packages/openmm/app/simulation.py", line 130, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/jsetiadi/anaconda3/envs/openmm-ml/lib/python3.7/site-packages/openmm/openmm.py", line 17881, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException: Error synchronizing CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS (700) at /home/conda/feedstock_root/build_artifacts/openmm-torch_1610987465997/work/platforms/cuda/src/CudaTorchKernels.cpp:94
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array globalParams: CUDA_ERROR_ILLEGAL_ADDRESS (700)
Aborted (core dumped)
```
So it looks like we need `openmm v7.5.1` + `openmm-torch rebuild with pytorch 1.8.0` + `the bug fix in torchani` for this to work.

**Comment by jaimergp** [comment]
I have built properly pinned packages for openmm-torch now.

* Build number 3 is built against PyTorch 1.7.1 and CUDA 10.2
* Build number 4 is built against PyTorch 1.8 and CUDA 11

If there are no ABI changes in OpenMM between 7.5 and 7.5.1, I *think* you could do:

```
conda create -n openmm-torch-pt18 -c conda-forge/label/openmm_rc -c conda-forge openmm-torch
conda activate openmm-torch-pt18
```

This *should* install OpenMM-Torch 0.1 build number 4, CUDA 11, OpenMM 7.5.1rc1 and PyTorch 1.8, which is hopefully what you need!

If you drop `-c conda-forge/label/openmm_rc`, then you'll get OpenMM 7.5, which should work if you work around that GIL issue.

**Comment by dominicrufa** [comment]
heads up: those 2 lines are conda installing pytorch 1.7.1:
![image](https://user-images.githubusercontent.com/46943710/113720327-8556ac00-96bc-11eb-81ef-86f8b23e98b4.png)

**Comment by jaimergp** [comment]
Can you force PyTorch 1.8?

```
conda create -n openmm-torch-pt18 -c conda-forge/label/openmm_rc -c conda-forge openmm-torch pytorch=1.8
```

**Comment by dominicrufa** [comment]
ah, it looks like following the [torchani pip installation](https://pypi.org/project/torchani/) updates to pytorch 1.8.1

**Comment by jaimergp** [comment]
I cannot guarantee that update works at all, given their different provenances and potential ABI incompatibilities. `torchani` should be distributed on `conda-forge` to ensure maximum compat.

**Comment by dominicrufa** [comment]
okay. let me go back and try again

**Comment by dominicrufa** [comment]
some conflicts:
![image](https://user-images.githubusercontent.com/46943710/113723818-b97f9c00-96bf-11eb-9aeb-32c8903fad7d.png)

**Comment by jaimergp** [comment]
For me, that command successfully resolves and creates an environment with the requested packages. Let's try two things:

If this is on Linux and there's a CUDA installation around, there's a chance the Nvidia drivers are not recent enough and are restricting `cudatoolkit` to 10.2, which is not available for the PyTorch 1.8 builds. If that's the case, this might work:

```
export CONDA_OVERRIDE_CUDA=11.0
conda create -n openmm-torch-pt18 -c conda-forge/label/openmm_rc -c conda-forge openmm-torch pytorch=1.8
```

However, the resulting environment might not be functional due to the oldish Nvidia drivers.

***
To debug this further:

* Which OS is this running on? Can you also paste the output of `conda info`? 
* Can you try installing `mamba` on your `base` environment:

```
conda install -n base -c conda-forge mamba
```

and then running

```
mamba create -n openmm-torch-pt18 -c conda-forge/label/openmm_rc -c conda-forge openmm-torch pytorch=1.8
```

This will give us a better understanding of the package conflicts.

**Comment by dominicrufa** [comment]
`mamba` FTW. i was running an outdated `conda` version. seems to work now!

**Comment by peastman** [comment]
I wasn't familiar with it.  It looks like it's basically conda, but faster and with more useful error messages?  Sounds like an improvement!

**Comment by jaimergp** [comment]
Yep! A C++ rewrite implementing the same CLI API, and some new bits here and there. QuantStack is doing great stuff in the `conda` world: https://github.com/mamba-org

**Comment by jeff231li** [comment]
Thanks @jaimergp for releasing a new version on conda. Closing this issue.
