### ISSUE TITLE
`TorchForce` object has no attribute `addGlobalParameter`

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-torch#28]
I'm trying to make a mixed system and tether a `scale` to the `TorchForce` as described [here](https://github.com/openmm/openmm-torch#defining-global-parameters-that-can-be-modified-within-the-context) but I'm seeing 
![image](https://user-images.githubusercontent.com/46943710/113800584-342ed280-9725-11eb-82a9-1f5e3fba7301.png). specifically, there is no `addGlobalParameter` when i `dir(openmmtorch.TorchForce)`. the `openmmtorch` is coming from the latest conda install

**Comment by peastman** [comment]
It looks like that feature just missed getting into the 0.1 release.  We should do a new release.

**Comment by dominicrufa** [comment]
okay. i think that is the last blocking thing for me.

**Comment by dominicrufa** [comment]
@peastman , @jaimergp built a new `openmm-torch` (attached) from the current master. it is conda-installable via 

```
conda create -n openmm-torch-0.2rc1 file.tar.gz
conda activate openmm-torch-0.2rc1
conda update --all -c conda-forge/label/openmm_rc -c conda-forge
```
,but it still doesnt have `addGlobalParameter` attr with the `TorchForce`. could you take a look?

[openmm-torch-0.2rc1-py39h64e9529_0.tar.gz](https://github.com/openmm/openmm-torch/files/6286183/openmm-torch-0.2rc1-py39h64e9529_0.tar.gz)

**Comment by dominicrufa** [comment]
ive been having trouble installing this from source. I'll only be able to test `opencl` if i can get manage to do that, though

**Comment by peastman** [comment]
That's fine.  It only has changes to the Python wrapper, so it doesn't matter what platform you use.

**Comment by dominicrufa** [comment]
```
>>> dir(openmmtorch.TorchForce)
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', 'addGlobalParameter', 'cast', 'getFile', 'getForceGroup', 'getGlobalParameterDefaultValue', 'getGlobalParameterName', 'getNumGlobalParameters', 'isinstance', 'setForceGroup', 'setGlobalParameterDefaultValue', 'setGlobalParameterName', 'setUsesPeriodicBoundaryConditions', 'thisown', 'usesPeriodicBoundaryConditions']
```
alright i was able to get `opencl` necessaries to install the PR from source after some troubles, and it seems that the appropriate python wrappers are in and define `addGlobalParameter` and the other necessary methods. @peastman, could you merge when you can? @jaimergp , could you build the conda package at your earliest convenience?

**Comment by peastman** [comment]
Merged!

**Comment by mikemhenry** [comment]
Thanks! Would you mind cutting a release os it gets picked up by conda-forge?

**Comment by jaimergp** [comment]
We'll need a tag + GitHub [release](https://github.com/openmm/openmm-torch/releases/tag/v0.1) for that.
