### ISSUE TITLE
`TorchForce`-augmented system has inconsistent forces

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-torch#32]
In attempting to make a `TorchForce` with a scale factor (as a global parameter) that acts on a subset of particles in a system, I encountered dynamics that nan pretty readily. Upon taking a closer look, I realized that there might be a problem in the way that the force matrix is computed?

To explain, I took a host-guest system (`mm_system`) from `openmmtools`, deepcopied it ( `ml_system`) and to the `ml_system` added a `TorchForce` which is a `torchani` `Module` that acts only on the guest atoms. To the module, I added a multiplicative scaling term that is defined by a global parameter. Upon defaulting the scale factor to zero, I computed the energies of the two systems (with the same positions) and found their energy discrepancies to be tolerable (a few thousandths of a kcal/mol), but I found that the force matrices are very different (should be non-discrepant, as well). I also noticed that the discrepant entries in the force matrix from the `ml_system` context don't even align with the particle entries that the `TorchForce` is acting on. The gist is attached [here](https://gist.github.com/dominicrufa/a4e1ed2188de53fb74449e4ce7bee04d). Any ideas? or am i doing something wrong?

Also, (not shown), when all of the forces (except the `HarmonicBondForce`) are removed from the systems, the force matrices do agree, and when the scale factor is nonzero, the force matrix of the `ml_system` has all zero entries (as expected) _except_ at the entries of the subset of particles on which the `TorchForce` is acting (which is consistent with what _should_ happen).

**Comment by peastman** [comment]
That's really puzzling.  The handling of the global parameter is all internal to the model.  If you multiply the energy by 0, that should also multiply the forces by 0.

I'm trying to reproduce this, but running into a lot of problems creating an environment with consistent versions of all the dependencies.  I'll keep working on that.  Meanwhile, could you try a few tests?

See whether the behavior varies by platform.  Try both Reference and CUDA.  Do they give the same results?

Try assigning each Force to a different force group, so you can query the force and energy from each one separately.  Where do the unexpected forces come from?  If you set the global parameter to 0, does the TorchForce report both force and energy as being 0?

**Comment by dominicrufa** [comment]
sorry i missed this yesterday. I made a much more stripped down version (simpler `TorchForce` and system) of the test [here](https://gist.github.com/dominicrufa/93997eb77c365022712e9f1beabcaddf) where I addressed the following suggestion:

>  If you multiply the energy by 0, that should also multiply the forces by 0.
it seems like (from the attached gist, the forces are still discrepant w.r.t. a control (no `TorchForce` modification)).

I'll try different platforms and different force groups as you suggested

**Comment by dominicrufa** [comment]
@jaimergp  gave me this conda-installable of the current working master: 
[omm.zip](https://github.com/openmm/openmm-torch/files/6401391/omm.zip)

**Comment by dominicrufa** [comment]
strangely, when i make the `TorchForce` group 1, the different force groups seem to calculate properly:

```
mm_forces = mm_context.getState(getForces=True).getForces(asNumpy=True)
ml_forces_g0 = ml_context.getState(getForces=True, groups={0}).getForces(asNumpy=True)
ml_forces_g1 = ml_context.getState(getForces=True, groups={1}).getForces(asNumpy=True)
```
at least with a `Reference` platform. I don't have CUDA locally, but will test on a cluster at some point today/tomorrow. 
I think i can get around this by making a custom integrator to handle the 'normal' forces separately from the `TorchForce`?

**Comment by peastman** [comment]
Let me see if I understand.  You're saying that if you put the TorchForce in a separate group and query the groups separately, each one gives correct forces.  But if you query the total force (omitting the `groups` argument), the force does not equal the sum of the two individual groups?  If that's correct, make sure there isn't some other force in a different group.

**Comment by dominicrufa** [comment]
> Let me see if I understand. You're saying that if you put the TorchForce in a separate group and query the groups separately, each one gives correct forces. But if you query the total force (omitting the groups argument), the force does not equal the sum of the two individual groups? If that's correct, make sure there isn't some other force in a different group.

precisely. and all forces are in group 0 except the `TorchForce`, which is group 1.

**Comment by dominicrufa** [comment]
as an update, it seems that running MD is unstable even when the `TorchForce` is scaled to 0. Also, it seems that running MD by only calculating forces from the non-`TorchForce` force group is unstable, as well.

**Comment by dominicrufa** [comment]
update : using a force-splitting scheme (by force group) in an MD integrator seems to fix the problem, as well.

**Comment by peastman** [comment]
I managed to get an environment set up where I can test this.  Everything in your notebook is working correctly for me.  In particular,

```python
mm_energy = mm_context.getState(getEnergy=True).getPotentialEnergy()
ml_energy = ml_context.getState(getEnergy=True).getPotentialEnergy()
mm_energy, ml_energy
```

produces the output

```
(Quantity(value=-51901.51563162469, unit=kilojoule/mole),
 Quantity(value=-51901.51563162469, unit=kilojoule/mole))
```

They're identical, because the scale factor for the TorchForce is 0 and it adds no energy.  Likewise,

```python
ml_forces = ml_context.getState(getForces=True).getForces(asNumpy=True)
ml_forces
```

produces the output

```
Quantity(value=array([[-0., -0., -0.],
       [-0., -0., -0.],
       [-0., -0., -0.],
       ...,
       [-0., -0., -0.],
       [-0., -0., -0.],
       [-0., -0., -0.]]), unit=kilojoule/(nanometer*mole))
```

as it should be.  This is using the Reference platform.  Is that different from what you see?
