### ISSUE TITLE
Making Neighborlist accessible

### ISSUE THREAD

**Issue by keano130** [openmm/openmm-torch#33]
I trained a model using the neural network from SchNetPack. This is a AtomisticModel, https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/atomistic/model.py. I would like to use this model in OpenMM for molecular modeling in python. The model requires not only the positions of the atoms, but also a neighborlist given a cutoff. Is it possible to acces the internal neighborlist of OpenMM. Otherwise i would need to use the neighborlist implemented in Schnetpack in TorchForce. This list would then update in every iteration, which is of course not necessary.
Therefore the question: Is it possible to solve this in a semi-efficient way, or is is necessary to rebuild the best Schnet model, using NNpops?

**Comment by peastman** [comment]
The internal neighbor list isn't in a form that would be suitable for this.  The last time I looked, SchNetPack didn't have a "real" neighbor list.  It was just a placeholder that included all interactions.  So it would be fine to just build it into the model.  It never needs updating.

**Comment by keano130** [comment]
I have a system with 304 atoms. I used the TorchEnvironmentProvider in https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/environment.py during the training. This is not a placeholder, in contrary to the SimpleEnvironmentProvider, which is also implemented in the same file.

**Comment by peastman** [comment]
Are you able to compile it to TorchScript?  If so, you should be able to include it as part of the model.

**Comment by keano130** [comment]
I will look into that, due to the exams coming up, I wont really have time to do this the coming two months. Thank you for the help!
