### ISSUE TITLE
update conda

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-torch#39]
@peastman , can you open a merge to conda forge. thanks!

**Comment by peastman** [comment]
Once I create the release, conda-forge will create a PR to build new packages automatically.  Can you verify the fix before I do that?

**Comment by dominicrufa** [comment]
yes, it's working.

**Comment by dominicrufa** [comment]
@peastman , can you get this is at your earliest convenience?

**Comment by peastman** [comment]
Sorry!  Conda-forge was supposed to have automatically created a PR to build the new packages, but for some reason it didn't.  I just created it manually.  https://github.com/conda-forge/openmm-torch-feedstock/pull/9

@jaimergp When I added the "please rerender" comment, it replied with a message that said, "I tried to rerender for you, but it looks like there was nothing to do."  Is that normal or does it mean something is wrong?

**Comment by jaimergp** [comment]
>  When I added the "please rerender" comment, it replied with a message that said, "I tried to rerender for you, but it looks like there was nothing to do." Is that normal or does it mean something is wrong?

That's normal. It means that the pinnings and scripts running the CI are already up-to-date 👌

**Comment by dominicrufa** [comment]
@peastman , it looks like you updated conda. can i close this issue? or you may :)
