### ISSUE TITLE
NNPOps linking issue

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-torch#45]
openmm-torch must be linked to NNPOps to be able to use it in torch runtime.

We need to find some way to dynamically load NNPOps library so symbols are available at the right now.

@raimis can correct this later

**Comment by raimis** [comment]
The linking issues has been resolved as demonstrated by a working tutorial: https://github.com/openmm/openmm-torch/blob/master/tutorials/openmm-torch-nnpops.ipynb
