### ISSUE TITLE
Move to openmm org?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-torch#5]
Would it make sense to move this repo and the TensorFlow-based repo to the http://github.com/openmm org?

**Comment by giadefa** [comment]
Is this already available in the main repo? We are going to use it now.

**Comment by peastman** [comment]
What do you mean by the main repo?

**Comment by giadefa** [comment]
currently it´s in your personal github. I mean is it officially supported
by openmm? If one get the released version for instance, is it there?

g

**Comment by jchodera** [comment]
@giadefa : I think this is currently an "experimental" plugin that must be compiled manually. There are no releases yet. Once things are stable, presumably we can cut a pre-release and see if we can get the `omnia` build framework to build a conda-installable package that would depend on the [`pytorch` channel package](https://anaconda.org/pytorch/pytorch).

**Comment by peastman** [comment]
I'll be transferring it to the openmm organization soon, once I do a bit of cleanup.  You should view this as alpha code.  I don't guarantee everything will work, but I'll do my best to fix any problems you find.  We'll do an official release once it's a bit more mature.

**Comment by peastman** [comment]
Also note that the PyTorch conda package doesn't include the C++ API.  This plugin depends on LibTorch, which currently is only available as a manual download.

**Comment by giadefa** [comment]
ok

**Comment by peastman** [comment]
Done.
