### ISSUE TITLE
Changing a module's state from context

### ISSUE THREAD

**Issue by bbharland** [openmm/openmm-torch#57]
I am trying to run a metadynamics simulation where the collective variables are defined by a network.  The ForceModule has two tensors which contain the heights and centres of the Gaussian bias terms, and I haven't been able to discover a way to add to these from the simulation context.

I've contemplated a few wrong ways, such as recompiling and substituting the module in the system, implementing the bias as a series of forces or abusing global parameters.  Is there a right way?

The business part of the module looks like this:
```
    def forward(self, positions):
        x = self.featurize(positions)
        s = self.net(x)
        return self.bias_potential(s)

    def featurize(self, positions):
        return torch.tensor([
            torch.sqrt(torch.sum(torch.square(positions[j] - positions[i])))
            for (i, j) in self.atom_pairs
            ]).reshape(1, -1)

    def bias_potential(self, s):
        w = torch.zeros(1)
        for hi, si in zip(self.heights, self.centers):
            ds = s - si
            w += hi * torch.exp(-0.5 * ds @ self.inv_sigma @ ds.t()).flatten()
        return w.item()
```

**Comment by raimis** [comment]
From the context you can pass atomic positions, simulation box vectors, and an arbitrary number of scalars (https://github.com/openmm/openmm-torch#defining-global-parameters-that-can-be-modified-within-the-context).

Probably the easiest approach is to update the bias within `ForceModule`.

**Comment by bbharland** [comment]
Thanks!  Just so I understand, are you suggesting that it would be possible to tell the ForceModule to update itself from the context?  Something like this:
`def update(self, positions):
    # add new Gaussian centred on s(positions)
`

**Comment by raimis** [comment]
Yes, `forward` can call `update` periodically.
