### ISSUE TITLE
conda-installed `openmm-torch` is not compatible with nightly `omnia-dev` `openmm` conda installation

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-torch#69]
```
Encountered problems while solving:
  - package openmm-torch-0.5-cuda112py39hb628e3f_0 requires openmm >=7.7.0,<7.8.0a0, but none of the providers can be installed
```
i installed `openmm-torch` from `conda-forge`, but it downgrades the nightly `openmm` installation. is there a workaround? or can the specs of the `conda-forge` `openmm-torch` be updated?

**Comment by raimis** [comment]
The pins of `openmm-torch` are exactly as they should for `conda-forge`. There is no a general way to make compatible with other arbitrary channels.

Short-term solution: you can try to circumvent the pins with `conda install --force-reinstall --no-deps`, but mostly likely it would results into broken environment due the binary incompatibilities. The more reliable way is just to build from source.

Long-term solution: set up the nightly builds of `openmm-torch`.

**Comment by raimis** [comment]
We maintain compatibility with the `conda-forge` channel only.
