### ISSUE TITLE
can't install from source following the instructions

### ISSUE THREAD

**Issue by wiederm** [openmm/openmm-torch#74]
Hi everyone!

I am trying to compile `openmm-torch` to use with the `omnia-dev ` openMM installation, but I keep running into issues.
I think I experience exactly the same issue as described [here](https://github.com/openmm/openmm-torch/issues/63), but neither of the two solutions outlined [here](https://github.com/openmm/openmm-torch/issues/63#issuecomment-1034602470) resolve the issue.

The error I get is:
```
[  3%] Building CXX object CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForce.cpp.o
[  6%] Building CXX object CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForceImpl.cpp.o
[ 10%] Building CXX object CMakeFiles/OpenMMTorch.dir/serialization/src/TorchForceProxy.cpp.o
[ 13%] Building CXX object CMakeFiles/OpenMMTorch.dir/serialization/src/TorchSerializationProxyRegistration.cpp.o
[ 16%] Linking CXX shared library libOpenMMTorch.so
[ 16%] Built target OpenMMTorch
[ 20%] CMake-copying file /data/shared/software/openmm-torch/tests/central.pt to /data/shared/software/openmm-torch/build/tests/central.pt
[ 23%] CMake-copying file /data/shared/software/openmm-torch/tests/forces.pt to /data/shared/software/openmm-torch/build/tests/forces.pt
[ 26%] CMake-copying file /data/shared/software/openmm-torch/tests/global.pt to /data/shared/software/openmm-torch/build/tests/global.pt
[ 30%] CMake-copying file /data/shared/software/openmm-torch/tests/periodic.pt to /data/shared/software/openmm-torch/build/tests/periodic.pt
[ 30%] Built target CopyTestFiles
[ 33%] Building CXX object serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o
[ 36%] Linking CXX executable ../../TestSerializeTorchForce
CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: In function `testSerialization()':
TestSerializeTorchForce.cpp:(.text+0x376): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestSerializeTorchForce.cpp:(.text+0x463): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestSerializeTorchForce.cpp:(.text+0x550): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestSerializeTorchForce.cpp:(.text+0x681): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestSerializeTorchForce.cpp:(.text+0x79a): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o:TestSerializeTorchForce.cpp:(.text+0x8ac): more undefined references to `OpenMM::throwException(char const*, int, std::string const&)' follow
CMakeFiles/TestSerializeTorchForce.dir/TestSerializeTorchForce.cpp.o: In function `void OpenMM::XmlSerializer::serialize<TorchPlugin::TorchForce>(TorchPlugin::TorchForce const*, std::string const&, std::ostream&)':
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo]+0x66): undefined reference to `OpenMM::SerializationNode::setName(std::string const&)'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo]+0xc9): undefined reference to `OpenMM::SerializationNode::hasProperty(std::string const&) const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo]+0x100): undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo]+0x150): undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
TestSerializeTorchForce.cpp:(.text._ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo[_ZN6OpenMM13XmlSerializer9serializeIN11TorchPlugin10TorchForceEEEvPKT_RKSsRSo]+0x18d): undefined reference to `OpenMM::SerializationNode::setStringProperty(std::string const&, std::string const&)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::setBoolProperty(std::string const&, bool)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getDoubleProperty(std::string const&) const'
../../libOpenMMTorch.so: undefined reference to `torch::jit::load(std::string const&, c10::optional<c10::Device>)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationProxy::SerializationProxy(std::string const&)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getBoolProperty(std::string const&) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getName() const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::setDoubleProperty(std::string const&, double)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&, int) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::Platform::createKernel(std::string const&, OpenMM::ContextImpl&) const'
../../libOpenMMTorch.so: undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::string const&)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::setIntProperty(std::string const&, int)'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::getStringProperty(std::string const&) const'
../../libOpenMMTorch.so: undefined reference to `OpenMM::SerializationNode::createChildNode(std::string const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [TestSerializeTorchForce] Error 1
make[1]: *** [serialization/tests/CMakeFiles/TestSerializeTorchForce.dir/all] Error 2
make: *** [all] Error 2
```
I have used the conda environment outlined [here](https://github.com/openmm/openmm-torch/issues/63#issuecomment-1034602470) as build environment, I am using `gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)` and the correct `libtorch` version as far as I can tell (`libtorch-cxx11-abi-shared-with-deps-1.11.0+cu102.zip`).
Any idea what I am doing wrong here? Any help is highly appreciated!

**Comment by peastman** [comment]
All the symbols it's not finding involving strings, so that definitely sounds like an issue with the C++11 ABI.  I just downloaded one of the most recent dev builds and confirmed it was built correctly.  For example, it contains the symbol `_ZN6OpenMM17SerializationNode15createChildNodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` which demangles to `OpenMM::SerializationNode::createChildNode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`.  Note the `__cxx11` in it, which is how you can tell it's using the C++11 ABI.

So we need to figure out why it's using the wrong ABI when you compile OpenMM-Torch.  The CMake script includes the line

https://github.com/openmm/openmm-torch/blob/51615ebb87bf8d8ad4e9a8e1f97d4b5f122f2116/CMakeLists.txt#L19

which I think is supposed to be sufficient?

In CMake, try editing the variable `CMAKE_CXX_FLAGS_RELEASE` to add the additional flag ` -D_GLIBCXX_USE_CXX11_ABI`.

**Comment by wiederm** [comment]
This is super strange. 
I have tried with `-D_GLIBCXX_USE_CXX11_ABI`, `-D_GLIBCXX_USE_CXX11_ABI=0` and `-D_GLIBCXX_USE_CXX11_ABI=1` as values for `CMAKE_CXX_FLAGS_RELEASE` and set the build type to `Release`. But somehow this does not change anything and the error is the same.
I have tried this also with a new conda environment, new `openmm-torch`  download to make sure that there is no cache file I am missing, and the `openMM` package from `conda-forge`.

**Comment by raimis** [comment]
@wiederm which GCC version are you using? Do you install it with Conda?

**Comment by wiederm** [comment]
I am able to build the package now! 
My previous build environment was on a CentOs7 machine and I followed this [answer](https://stackoverflow.com/questions/55345373/how-to-install-gcc-g-8-on-centos) to activate the Developer Toolset and GCC 8. But I guess somehow this was not enough.
I just updated to CentOs8 and suddenly I am able to build the package without any issue (also using GCC 8.5)! Thank you very much for your help!

**Comment by peastman** [comment]
Very strange!  I'm glad you've got it working now.  I'll go ahead and close this.  Feel free to reopen it if the problem reappears.

**Comment by raimis** [comment]
> My previous build environment was on a CentOs7 machine and I followed this [answer](https://stackoverflow.com/questions/55345373/how-to-install-gcc-g-8-on-centos) to activate the Developer Toolset and GCC 8. But I guess somehow this was not enough.

There is nothing strage here: CentOS 7 compilers are hardcoded to build with the old  C++ ABI regardless of `_GLIBCXX_USE_CXX11_ABI`. CentOS 8 changed to the new C++ ABI.

**Comment by kexul** [comment]
Dear developers, is it possible to build it under centos 7?
