### ISSUE TITLE
Stress support

### ISSUE THREAD

**Issue by davkovacs** [openmm/openmm-torch#91]
We have several projects that would greatly benefit from openmm-torch supporting ML models returning stress (not only energy and forces). This way we could use OpenMM for running NPT simulations using ML force fields.

**Comment by raimis** [comment]
You can already use `TorchForce` for the NPT simulations. The barostats in OpenMM don't need stresses.

**Comment by davkovacs** [comment]
Sorry, I did not realise OpenMM uses a Monte Carlo barostat. In that case there is no problem. We will give it a go.
